# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir O:/Documents/GameofLifeMoving/GameofLifeMoving.cache/wt [current_project]
set_property parent.project_path O:/Documents/GameofLifeMoving/GameofLifeMoving.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo o:/Documents/GameofLifeMoving/GameofLifeMoving.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files O:/Documents/GameofLifeMoving/GameofLifeMoving.srcs/sources_1/imports/Documents/testcoeGOL.coe
read_vhdl -library xil_defaultlib {
  O:/Documents/GameofLifeMoving/GameofLifeMoving.srcs/sources_1/new/Input_Controller.vhd
  O:/Documents/GameofLifeMoving/GameofLifeMoving.srcs/sources_1/new/PixelGenerator.vhd
  O:/Documents/GameofLifeMoving/GameofLifeMoving.srcs/sources_1/imports/Documents/VGATestConsolidated2/VGATestConsolidated2.srcs/sources_1/imports/Desktop/result/design.vhd
  O:/Documents/GameofLifeMoving/GameofLifeMoving.srcs/sources_1/new/game_controller.vhd
  O:/Documents/GameofLifeMoving/GameofLifeMoving.srcs/sources_1/imports/Documents/VGATestConsolidated2/VGATestConsolidated2.srcs/sources_1/new/VGATestTopLevel.vhd
}
read_ip -quiet O:/Documents/GameofLifeMoving/GameofLifeMoving.srcs/sources_1/ip/old_state_RAM/old_state_RAM.xci
set_property used_in_implementation false [get_files -all o:/Documents/GameofLifeMoving/GameofLifeMoving.srcs/sources_1/ip/old_state_RAM/old_state_RAM_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc O:/Documents/GameofLifeMoving/GameofLifeMoving.srcs/constrs_1/imports/Desktop/VGAConnections.xdc
set_property used_in_implementation false [get_files O:/Documents/GameofLifeMoving/GameofLifeMoving.srcs/constrs_1/imports/Desktop/VGAConnections.xdc]


synth_design -top VGATestTopLevel -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef VGATestTopLevel.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file VGATestTopLevel_utilization_synth.rpt -pb VGATestTopLevel_utilization_synth.pb"
