# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: o:/Documents/GameOfLifeDisplay/GameOfLifeDisplay.srcs/sources_1/ip/old_state_RAM/old_state_RAM.xci
# IP: The module: 'old_state_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: o:/Documents/GameOfLifeDisplay/GameOfLifeDisplay.srcs/sources_1/ip/old_state_RAM/old_state_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'old_state_RAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: o:/Documents/GameOfLifeDisplay/GameOfLifeDisplay.srcs/sources_1/ip/old_state_RAM/old_state_RAM.xci
# IP: The module: 'old_state_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: o:/Documents/GameOfLifeDisplay/GameOfLifeDisplay.srcs/sources_1/ip/old_state_RAM/old_state_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'old_state_RAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
